version: '3'
services:
  journal:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      GIT_REPO: ${GIT_REPO}
      GIT_NAME: ${GIT_NAME}
      GIT_USERNAME: ${GIT_USERNAME}
      GIT_EMAIL: ${GIT_EMAIL}
      GIT_TOKEN: ${GIT_TOKEN}